"""
import_helper.py
- provides helper functions for importing

LibreBulletin automated bulletin generation
By Gabriel Staples
https://github.com/ElectricRCAircraftGuy/LibreBulletin
"""

def extract_config_file_from_inputs(bulletin_INPUTS_path, demo):
    """
    Extract out config.py from the bulletin_INPUTS text file and place it into the correct
    "autogenerated" folder.
    """
    print('Extracting config.py portion of file out of "{}".'.format(bulletin_INPUTS_path))

    file = open(bulletin_INPUTS_path, "r")
    text = file.read()
    file.close()

    # Extract the config.py portion of the file (all contents after a given delimiter string)
    delimiter = '==PYTHON CODE config.py START--DO NOT MODIFY THIS LINE=='
    print('  Searching for delimiter: "{}".'.format(delimiter))
    if (delimiter not in text):
        print("  ERROR: delimiter not found in file. Exiting program.")
        exit()
    max_num_splits = 1
    config_file_str = text.split(delimiter, max_num_splits)[-1]

    # Save config.py
    if (demo == True):
        savepath = './autogenerated/config.py'
    else:
        savepath = './MY_PERSONAL_WARD_INFO/autogenerated/config.py'
    print('  Writing file to "{}".'.format(savepath))
    file = open(savepath, "w")
    file.write(config_file_str)
    file.close()
    print('  Done.')









